version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mc-dicri-db
    environment:
      SA_PASSWORD: "7J((s&53qG7"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql
      - ./mssqldb/script_inicio.sql:/tmp/script_inicio.sql
      - ./mssqldb/init-db.sh:/tmp/init-db.sh
    networks:
      - appnet

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mc-dicri-api
    depends_on:
      - db
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - DB_HOST=db
      - DB_USER=forense_app_user
      - DB_PASSWORD=73>ysO72eQL0
      - DB_NAME=forense_app
    networks:
      - appnet

  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mc-dicri-front
    depends_on:
      - api
    ports:
      - "8080:80"
    volumes:
      - ./frontend/public/config.js:/usr/share/nginx/html/config.js
    networks:
      - appnet

networks:
  appnet:

volumes:
  mssqldata:
